PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

PREFIX accesspoint: <http://central.biomart.org/martsemantics/hgnc_config/ontology#>
PREFIX class: <biomart://central.biomart.org/martsemantics/hgnc_config/ontology/class#>
PREFIX dataset: <biomart://central.biomart.org/martsemantics/hgnc_config/ontology/dataset#>
PREFIX attribute: <biomart://central.biomart.org/martsemantics/hgnc_config/ontology/attribute#>

SELECT ?a0 ?a1 ?a2 
FROM dataset:hgnc
WHERE {
  ?mart attribute:gd_app_name ?a0 .
  ?mart attribute:gd_prev_name ?a1 .
  ?mart attribute:gd_ccds_ids ?a2
}
LIMIT 10
